process-analytics/process-analytics.dev

gatsby-browser.js, src/content/AboutContent.tsx, src/theme/sections/About.tsx, src/theme/types.ts
- Remove the animation on the image on hover
- Remove empty global.css file
- Rename property `profile` in `About` to `logo`
=> [FEAT] Remove the image animation in the about section

src/theme/sections/About.tsx
=> [FEAT] Set logo size in About section for desktop and mobile

src/content/LibraryContent.tsx, src/theme/components/Library.tsx, src/theme/types.ts
Add bpmn-layout-generator and mxgraph
The example property is now optional
Provide more space for the lib description
=> [FEAT] Display more libraries

src/theme/components/Card.tsx
- Add border on Card 
- Remove box-shadow on not hover
Covers #22
=> [FEAT] Add border to better highlight card on white background

src/pages/404.tsx
=> [FEAT] Set image size in 404 page for desktop and mobile

gatsby-config.js, package-lock.json, package.json
=> [FEAT] Setup analytics (visits and views)

src/content/PostsContent.tsx, src/theme/components/Post.tsx
=> [FEAT] Add blog posts about process discovery to BPMN

src/theme/sections/About.tsx
Need to refactor the code in another PR to build the image subsection with only one class.
=> [FIX] Fix the animation of the image & the margin on mobile

.github/workflows/deploy.yml, .github/workflows/generate-site-preview.yml, .gitignore, gatsby-config.js, src/theme/components/Layout.tsx
- Configure the environment variable for the GA Id in `Gatsby`, like : https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables/
- Configure the secrets for the GA Id in Github
- Configure the environment variable for the GA Id in the Github actions from the Gihub secrets
Closes #70
=> [FEAT] Have separate accounts for Google analytics for the different environment

src/content/HelmetContent.tsx, src/content/LandingContent.tsx, src/theme/components/Footer.tsx, src/theme/components/Header.tsx, src/theme/components/Helmet.tsx
Clean meta generated by Helmet
Include a meta tag for google console verification
covers #22
covers #54
closes #58
=> [FEAT] Update meta for page and card

src/theme/components/Divider.tsx, src/theme/components/description/DescriptionPanel.tsx, src/theme/components/description/ImagePanel.tsx, src/theme/components/description/MDXPanel.tsx, src/theme/sections/About.tsx
=> [FEAT] Improve the website rendering in mobile format

src/content/LibraryContent.tsx
Closes https://github.com/process-analytics/bpmn-visualization-R/issues/3
=> [FEAT] Update the R library information

src/content/NewsContent.tsx, src/content/PostsContent.tsx
move 'bpmn-visualization 1st anniversary' from posts to news
news: add hacktoberfest 2020
posts: add 'github actions'
=> [FEAT] Add blog posts and news

src/theme/components/Post.tsx
Change the message about the time to read to make it more explicit.
=> [FEAT] Improve blogs and news card footer

src/content/LibraryContent.tsx, src/theme/components/Library.tsx, src/theme/icons.ts, src/theme/types.ts
Also update the 'examples' link: use plural in both code and tooltip.
closes #247
=> [FEAT] Add documentation in library card

.github/dependabot.yml
=>  [INFRA] Update dependabot reviewers

src/content/NewsContent.tsx
The news image size is 61,79 Kb.
=> [FEAT] Add February 2022 news

.github/workflows/build-pr.yml, .github/workflows/deploy.yml, .github/workflows/generate-site-preview.yml, src/content/about_content_1.mdx
Add the `--legacy-peer-deps` option to avoid issue with `gatsby-plugin-mdx` that requires an old version of react.
See https://github.com/process-analytics/process-analytics.dev/pull/544#issuecomment-1154810389
=> [INFRA] Avoid issue with peerDependencies

package-lock.json, package.json, src/content/HeaderContent.tsx, src/pages/404.tsx, src/pages/index.tsx, src/pages/model-generation-application-conditions.tsx, src/pages/model-generation-application.tsx, src/theme/components/Header.tsx, src/theme/components/Layout.tsx, src/theme/components/PageHeader.tsx, src/theme/pages/PageWithPosts.tsx
5th PR to implement the new theme from the POC https://github.com/process-analytics/process-analytics.dev/pull/424
| Before | Now |
| ------- | ----- |
| ![image](https://user-images.githubusercontent.com/4921914/218074600-30b887d8-97f5-43e8-9eab-b3c61fc5bf87.png) | ![image](https://user-images.githubusercontent.com/4921914/218074668-6921c1df-eceb-4c4a-990b-f2be52216174.png) |
|  ![image](https://user-images.githubusercontent.com/4921914/218074911-a464bbde-289b-44fb-8144-9ab1d1086af9.png) |  ![image](https://user-images.githubusercontent.com/4921914/218074859-23500903-f885-40bb-9b18-ef541bf2f31b.png) |
=> feat: introduce new page headers

src/pages/index.tsx, src/theme/icons.ts, src/theme/sections/Landing.tsx, src/theme/sections/Libraries.tsx, src/theme/sections/ModelGenerationApp.tsx, src/theme/sections/index.ts, src/theme/utils/constants.ts
7th PR to implement the new theme from the POC https://github.com/process-analytics/process-analytics.dev/pull/424
⚠️ The background will change with the new theme.
| Before | Now |
| ------- | ----- |
| ![image](https://user-images.githubusercontent.com/4921914/219088248-dd4421e2-e4a7-45dc-85a3-ea74bfcb490f.png) | ![image](https://user-images.githubusercontent.com/4921914/219088449-d5490e91-e755-4ebf-9717-20d046cbef28.png) |
=> feat: split the landing section in 2 sections

src/theme/components/material-kit/Navbar/Navbar.tsx, src/theme/components/material-kit/Navbar/common/ActionButton.tsx, src/theme/components/material-kit/Navbar/common/BrandLink.tsx, src/theme/components/material-kit/Navbar/common/NavbarItem.tsx, src/theme/components/material-kit/Navbar/common/NavbarItems.tsx, src/theme/components/material-kit/Navbar/common/index.tsx, src/theme/components/material-kit/Navbar/mobile/NavbarNav.tsx
Just some refactoring to clean the code
=> refactor(navbar): split navbar and move common components

src/theme/components/material-kit/Navbar/Navbar.tsx, src/theme/components/material-kit/Navbar/common/NavbarItem.tsx, src/theme/components/material-kit/Navbar/common/NavbarItems.tsx, src/theme/components/material-kit/Navbar/mobile/DropdownDropdown.tsx, src/theme/components/material-kit/Navbar/mobile/DropdownLink.tsx, src/theme/components/material-kit/Navbar/mobile/NavDropdown.tsx, src/theme/components/material-kit/Navbar/mobile/NavLink.tsx, src/theme/components/material-kit/Navbar/mobile/NavbarButton.tsx, src/theme/components/material-kit/Navbar/mobile/NavbarNav.tsx
Just some refactoring to clean the code
=> refactor(navbar): clean mobile navbar components

src/theme/components/Section.tsx
=> fix(mobile): remove the extra color blocks on right

.github/workflows/build-pr.yml, .github/workflows/deploy.yml
Fix the format of the data on .env.production file, created by the Build PR workflow and the Deploy workflow.
=> chore: Fix Deploy and Build PR workflows

src/theme/components/material-kit/Navbar/Navbar.tsx, src/theme/components/material-kit/Navbar/common/HoverStyle.tsx, src/theme/components/material-kit/Navbar/common/NavbarItem.tsx, src/theme/components/material-kit/Navbar/desktop/Dropdown.tsx, src/theme/components/material-kit/Navbar/desktop/DropdownMenu.tsx, src/theme/components/material-kit/Navbar/desktop/NavbarItems.tsx, src/theme/components/material-kit/Navbar/desktop/NestedDropdownMenu.tsx, src/theme/components/material-kit/Navbar/mobile/DropdownDropdown.tsx, src/theme/components/material-kit/Navbar/mobile/DropdownLink.tsx, src/theme/components/material-kit/Navbar/mobile/NavDropdown.tsx, src/theme/components/material-kit/Navbar/mobile/NavLink.tsx, src/theme/components/material-kit/Navbar/mobile/NavbarNav.tsx
Now, it's possible to configure the style of the hover on the navbar.
The behavior shouldn't have change.
=> refactor: make the hover configurable on the navbar components

src/theme/components/Header.tsx
=> refactor(theme): remove the unnecessary ThemeProvider on the Header component

src/content/FooterContent.tsx, src/content/LandingContent.tsx, src/content/SocialLinkContent.tsx, src/sections/home/Landing.tsx, src/theme/components/Footer.tsx, src/theme/components/SocialLink.tsx, src/theme/components/index.tsx, src/theme/types.ts
=> refactor(props): refactor social link props

src/components/seo.tsx, src/content/LandingContent.tsx, src/sections/home/Landing.tsx, src/theme/types.ts
=> refactor(props): refactor landing props

src/content/NewsContent.tsx, src/content/PostsContent.tsx, src/pages/blog.tsx, src/pages/model-generation-application.tsx, src/pages/news.tsx, src/sections/SectionWithPosts.tsx, src/sections/home/Blog.tsx, src/sections/home/News.tsx, src/theme/components/PostContainer.tsx, src/theme/components/index.tsx, src/theme/pages/PageWithPosts.tsx, src/theme/types.ts
=> refactor(props): refactor post props

src/components/material-kit/Navbar/Navbar.tsx, src/components/material-kit/Navbar/desktop/Dropdown.tsx, src/components/material-kit/Navbar/desktop/DropdownDropdown.tsx, src/components/material-kit/Navbar/desktop/NavDropdown.tsx, src/components/material-kit/Navbar/desktop/NavbarNav.tsx, src/components/material-kit/Navbar/desktop/index.tsx
=> refactor(navbar): rename navbar components

src/components/material-kit/Navbar/Navbar.tsx, src/components/material-kit/Navbar/common/HoverStyle.tsx
=> refactor(navbar): refactor props of Navbar component

src/components/material-kit/Navbar/desktop/Dropdown.tsx
=> refactor(navbar): introduce DropdownProps

src/components/material-kit/Navbar/desktop/Dropdown.tsx, src/components/material-kit/Navbar/desktop/navDropdown/ColumnDropdownMenus.tsx, src/components/material-kit/Navbar/desktop/navDropdown/ListDropdownMenus.tsx, src/components/material-kit/Navbar/desktop/navDropdown/NavDropdown.tsx, src/components/material-kit/Navbar/desktop/navDropdown/index.ts
=> refactor(navbar): split navDropdown file 

src/components/material-kit/Navbar/desktop/DropdownDropdown.tsx, src/components/material-kit/Navbar/desktop/DropdownLink.tsx, src/components/material-kit/Navbar/desktop/navDropdown/ListDropdownMenus.tsx
=> refactor(navbar): split DropdownDropdown file

src/components/material-kit/Navbar/desktop/navDropdown/ColumnNavDropdown.tsx, src/components/material-kit/Navbar/desktop/navDropdown/NavDropdown.tsx
=> refactor(navbar): rename ColumnDropdownMenus in ColumnNavDropdown

src/components/material-kit/Navbar/desktop/navDropdown/ListNavDropdown.tsx, src/components/material-kit/Navbar/desktop/navDropdown/NavDropdown.tsx
=> refactor(navbar): rename ListDropdownMenus in ListNavDropdown

src/components/material-kit/Navbar/desktop/navDropdown/ListNavDropdown.tsx, src/components/material-kit/Navbar/desktop/navDropdown/NavDropdown.tsx
=> refactor(navbar): convert ListNavDropdown in component function

src/components/material-kit/Navbar/desktop/navDropdown/ColumnNavDropdown.tsx, src/components/material-kit/Navbar/desktop/navDropdown/NavDropdown.tsx
=> refactor(navbar): convert ColumnNavDropdown in component function

src/components/material-kit/Navbar/desktop/navDropdown/ColumnNavDropdown.tsx
=> refactor(navbar): split column navDropdown function for desktop view

src/components/material-kit/Navbar/desktop/Dropdown.tsx, src/components/material-kit/Navbar/desktop/navDropdown/NavDropdown.tsx
=> refactor(navbar): avoid to send the state to the component children for the desktop component

src/components/material-kit/Navbar/common/NavLink.tsx, src/components/material-kit/Navbar/common/index.tsx, src/components/material-kit/Navbar/desktop/NavbarNav.tsx, src/components/material-kit/Navbar/mobile/NavbarNav.tsx
=> refactor(navbar): mutualize common component for mobile & desktop views

src/components/material-kit/Navbar/desktop/columnNavDropdown/Column.tsx, src/components/material-kit/Navbar/desktop/columnNavDropdown/ColumnNavDropdown.tsx, src/components/material-kit/Navbar/desktop/columnNavDropdown/DropdownDropdown.tsx, src/components/material-kit/Navbar/desktop/columnNavDropdown/DropdownItem.tsx, src/components/material-kit/Navbar/desktop/navDropdown/NavDropdown.tsx
=> refactor(navbar): split ColumnNavDropdown component and file

src/components/Header.tsx, src/components/material-kit/Navbar/Navbar.tsx, src/components/material-kit/Navbar/desktop/Dropdown.tsx, src/components/material-kit/Navbar/desktop/DropdownDropdown.tsx, src/components/material-kit/Navbar/desktop/DropdownLink.tsx, src/components/material-kit/Navbar/desktop/NavbarNav.tsx, src/components/material-kit/Navbar/desktop/columnNavDropdown/DropdownItem.tsx, src/components/material-kit/Navbar/desktop/listNavDropdown/DropdownDropdown.tsx, src/components/material-kit/Navbar/desktop/listNavDropdown/DropdownLink.tsx, src/components/material-kit/Navbar/desktop/listNavDropdown/ListNavDropdown.tsx, src/components/material-kit/Navbar/desktop/navDropdown/NavDropdown.tsx, src/components/material-kit/Navbar/mobile/DropdownDropdown.tsx, src/components/material-kit/Navbar/mobile/NavbarNav.tsx
=> refactor(navbar): change some props

src/components/Header.tsx, src/components/material-kit/Navbar/desktop/DropdownDropdown.tsx, src/components/material-kit/Navbar/desktop/columnNavDropdown/DropdownItem.tsx, src/components/material-kit/Navbar/mobile/DropdownDropdown.tsx, src/components/material-kit/Navbar/mobile/DropdownLink.tsx, src/components/material-kit/Navbar/mobile/NavDropdown.tsx
=> refactor(navbar): change missing props

src/components/Library.tsx, src/components/PageWithPosts.tsx, src/components/description/DescriptionPanel.tsx, src/components/description/ImagePanel.tsx, src/components/description/MDXPanel.tsx, src/components/description/index.ts, src/components/index.tsx, src/components/mailingListSubscription/MailingListSubscription.tsx, src/components/mailingListSubscription/index.ts, src/components/material-kit/index.tsx, src/content/FooterContent.tsx, src/pages/404.tsx, src/pages/blog.tsx, src/pages/index.tsx, src/pages/model-generation-application-conditions.tsx, src/pages/model-generation-application.tsx, src/pages/news.tsx, src/sections/SectionWithPosts.tsx, src/sections/home/About.tsx, src/sections/home/Blog.tsx, src/sections/home/Landing.tsx, src/sections/home/Libraries.tsx, src/sections/home/News.tsx
=> refactor: have default named component in each file

src/components/PageWithPosts.tsx, src/components/seo.tsx, src/content/index.ts, src/pages/404.tsx, src/pages/blog.tsx, src/pages/index.tsx, src/pages/model-generation-application-conditions.tsx, src/pages/model-generation-application.tsx, src/pages/news.tsx, src/sections/home/Blog.tsx, src/sections/home/Landing.tsx, src/sections/home/Libraries.tsx, src/sections/home/News.tsx
=> refactor: add `index` file on `content` folder

.github/workflows/build-pr.yml, .github/workflows/generate-site-preview.yml, gatsby-config.ts
=> feat(gatsby): change the colors in the Gatsby configuration

src/components/Button.tsx, src/components/PostContainer.tsx, src/components/index.tsx
=> feat(button): use MaterialUI in the Button component

src/components/PostContainer.tsx
=> feat(post): use MaterialUI in PostContainer component 

src/components/PageWithPosts.tsx, src/pages/blog.tsx, src/pages/news.tsx
=> feat(post): use MaterialUI in PageWithPosts component

src/pages/404.tsx
⚠️ The text can have not the same font size as the original design, due to the Typography of Material Kit. 
=> feat(page): use MaterialUI in the  404 page

src/sections/home/Landing.tsx
⚠️ The text can have not the same font size as the original design, due to the Typography of Material Kit.
=> feat(page): use MaterialUI in the Landing section

src/components/Footer.tsx, src/components/SocialLink.tsx, src/components/index.tsx
Based on our team's decision, we no longer require approval of the refactoring pull request. Instead, we will review and approve the refactoring once all changes related to a specific component have been completed.  
⚠️ The text can have not the same font size as the original design, due to the Typography of Material Kit.  
Covers #831
=> feat(social link): use MaterialUI in SocialLink component

src/components/SEO.tsx, src/components/index.tsx
Based on our team's decision, we no longer require approval of the refactoring pull request. Instead, we will review and approve the refactoring once all changes related to a specific component have been completed.  
⚠️ The text can have not the same font size as the original design, due to the Typography of Material Kit.  
Covers #831
=> feat(seo): use MaterialUI in the SEO component

src/components/description/ImagePanel.tsx, src/components/description/MDXPanel.tsx
=> feat(mdx): use MaterialUI in the image & the box components for the MDX content

src/assets/theme/base/typography.ts, src/assets/theme/responsiveFont.ts
=> fix(font): fix responsive font

src/components/material-kit/Card/LibraryCard.tsx
I modified the layout of the Library card for the mobile view. Additionally, I reduced the size of the icon in the process.  
=> fix(card): fix library card rendering on mobile view

src/content/SocialLinkContent.tsx, src/helper/icons.ts
This will be my last pull request related to design improvements for a while 🙂 .
=> feat(logo): replace the Twitter logo with its new (X)

package-lock.json, package.json
=> chore: remove unnecessary dependency @fontsource/open-sans

package-lock.json, package.json
ℹ️ Based on our team's decision, we no longer require approval of the refactoring pull request. Instead, we will review and approve the refactoring once all changes related to a specific component have been completed.
=> chore: remove unnecessary dependency: @types/react-headroom

src/content/SocialLinkContent.tsx, src/helper/icons.ts
<table><tbody><tr><td>Before</td><td>Now</td></tr><tr><td><figure class="image"><img src="https://github.com/user-attachments/assets/b56056fd-e22a-4816-90ab-67f0b7504bd8"></figure></td><td><figure class="image"><img src="https://github.com/user-attachments/assets/718bd28f-f45b-42f2-904e-f2ecf542eca0"></figure></td></tr></tbody></table>
=> feat: remove Discord link
