process-analytics/process-analytics.dev

- src/theme/sections/About.tsx
`Warning: Each child in a list should have a unique "key" prop`
> [FIX] Fix a warning on the SubSection of About section

- .github/workflows/deploy.yml
- gatsby-config.js
- package-lock.json
- package.json
Use .env.production file to define environment variable only set on the live site.
By default, on surge.sh preview deployments, the generated robots.txt file disallow all content.
closes #14
> [FEAT] Configure robots.txt

- package-lock.json
- package.json
- src/theme/components/SocialLink.tsx
The dependency `@tippy.js/react` is deprecated: https://www.npmjs.com/package/@tippy.js/react
The package has moved to [@tippyjs/react](https://www.npmjs.com/package/@tippyjs/react).
> [INFRA] Replace @tippy.js/react by @tippyjs/react

- src/content/PostsContent.tsx
Size of the image used to present the article: 38kb
With this new entry, we will have 9 referenced blog posts. It becomes urgent implementing #187
> [FEAT] Add blog post 'mxgraph in TS project'

- src/pages/404.tsx
- src/pages/blog.tsx
- src/pages/index.tsx
- src/theme/components/Layout.tsx
- src/theme/components/PageHeader.tsx
- src/theme/sections/Blog.tsx
- src/theme/utils/constants.ts
Covers #187 
Accessible from : http://localhost:8000/blog and https://process-analytics-process-analytics-dev-site_preview-pr-224.surge.sh/blog
All page titles are updated and follow 'PAGE_NAME - Process Analytics', except the **Home** page which keeps 'Process Analytics'.
> [FEAT] Create the new 'Blog' page

- src/pages/blog.tsx
- src/theme/components/Card.tsx
- src/theme/components/Footer.tsx
- src/theme/components/Header.tsx
- src/theme/components/Link.tsx
- src/theme/components/PageHeader.tsx
- src/theme/components/Post.tsx
- src/theme/components/Section.tsx
- src/theme/rebass-preset.d.ts
- src/theme/sections/Blog.tsx
- src/theme/sections/News.tsx
- src/theme/theme.ts
Covers #187 
- Remove duplication between `Post` and `News` sections
- Merge `Post` and old `PostContainer` classes
- Add a content property in new `PostContainer` class: posts or news can be passed to the component
- The new `PostContainer` class has a new `pageId` property: when set, it limits the number of cards to 6 and create a 'More' button linked to the page passed as property
> [FEAT] Don't display all the posts in the 'Blog' section of the 'Home' page

- package-lock.json
- package.json
Revert "[INFRA] dev - Bump babel-plugin-styled-components from 1.13.3 to 2.0.1 (#236)"
This reverts commit 32e7f41a82c5745994c144f6ff16f62a7e6743e6.
> [FIX] The images in the About section were no longer displayed

- src/pages/404.tsx
- src/theme/components/PageHeader.tsx
In blog and news pages: remove links to posts and news in header
Use header, footer and mail subscription in the 404 page
covers #187
> [FEAT] Simplify header in non 'home' pages

- src/content/NewsContent.tsx
We now have more than 6 news, so the 'See All' button appear below the 'News' cards in the Home page.
> [FEAT] Add the December 2021 project news

- .github/dependabot.yml
Automatic rebases triggered too much GH Actions run, in particular for PR that are on hold because they require manual tests or changes (on breaking changes).
They used a lot of runners so we had job in queue for PR that we wanted to merge in priority.
Now, we ask dependabot to rebase a PR just prior we want to merge it.
**Notes**
Followup of https://github.com/process-analytics/bpmn-visualization-js/pull/1796
>  [INFRA] Disable dependabot PR auto rebase

- .github/workflows/generate-site-preview.yml
When closing the PR, the only thing to do is to run the surge teardown. So skip other actions in this case.
This is what is done in the [playground repository](https://github.com/process-analytics/github-actions-playground/blob/5d35937bbd5ac92a0bceda3ce313c7e698d895c3/.github/workflows/surge-preview-for-pr.yml#L28)
> [INFRA] Simplify surge preview teardown

- .eslintignore
It contains Gatsby generated resources.
> [INFRA] Ignore `.cache` when running eslint

- .github/workflows/deploy.yml
- .github/workflows/generate-site-preview.yml
based on work done in https://github.com/process-analytics/github-actions-playground/issues/30
closes #520
**_Workflow run permissions are read-only by default_**
> GITHUB_TOKEN Permissions
Metadata: read
PullRequests: write
> [INFRA] Configure workflow for default read contents permissions GH TOKEN

- src/content/PostsContent.tsx
The image was broken. The link has changed in the community.bonitasoft.com blog.
before | now
----- |  -----
1st proposal
> [FIX] Display the image of the 'layout generator' post

- .github/actions/build-setup/action.yml
- .github/workflows/build-pr.yml
- .github/workflows/deploy.yml
- .github/workflows/generate-site-preview.yml
Introduce a local action to manage the npm cache and dependencies installation. All workflows now
use it to ensure that the setup is done in same way everywhere.
The surge preview won't generate teardown errors when the domain doesn't exist. This occurred when
closing PR created by Dependabot.
closes  #546
see also https://github.com/process-analytics/bpmn-visualization-js/pull/2072
> [INFRA] Improve GitHub workflow and remove duplications

- CONTRIBUTING.md
> [DOC] fix 2 dead links

- .github/actions/build-setup/action.yml
- .npmrc
- README.md
- package-lock.json
Use a `.npmrc` configuration file instead of duplicating the npm options in the documentation and in GitHub workflows.
> [INFRA] Simplify usage of `npm install`

- package-lock.json
- package.json
Before to update Gastby to v5, we update all its plugins and itself on their last v4 version.
- gatsby to 4.24.8
- gatsby-plugin-google-gtag to 4.24.0
- gatsby-plugin-styled-components to 5.24.0
- gatsby-plugin-typescript to 4.24.0
> [INFRA] Update gatsby to 4.24.8

- .github/dependabot.yml
- .github/workflows/pr-metadata-checks.yml
- CONTRIBUTING.md
Add a dedicated workflow to enforce the rule. It runs on `pull_request_target` to handle PR created by Dependabot and from fork repositories.
Dependabot configuration: change PR title prefix.
Review the Contributing guide (fix typo).
closes #853
For tests, see https://github.com/process-analytics/github-actions-playground/issues/213
> chore: ensure that the PR title follows "Conventional Commits"

- src/pages/404.tsx
- src/pages/model-generation-application-conditions.tsx
- src/pages/model-generation-application.tsx
- src/theme/components/Section.tsx
- src/theme/pages/PageWithPosts.tsx
- src/theme/sections/About.tsx
- src/theme/sections/Blog.tsx
- src/theme/sections/Landing.tsx
- src/theme/sections/Libraries.tsx
- src/theme/sections/News.tsx
- src/theme/sections/SectionWithPosts.tsx
*   Rename `Section.Container` in `Section`
*   Rename `Section.Header` in `SectionHeader`
*   Export `Section`  and `SectionHeader` not as `default`
*   Introduce `SectionWithTitle` component
*   Rename `containerTitle` attribute in `SectionWithPosts` to `title`
> refactor: rename section components

- src/theme/utils/constants.ts
- src/theme/utils/string.ts
To be in the same order as in the `home` page.
| Before | Now |  
| ------- | ----- |  
| ![image](https://user-images.githubusercontent.com/4921914/220140431-5dce5ed1-6880-4611-84ad-728d2a41fc12.png) | ![image](https://user-images.githubusercontent.com/4921914/220140358-5894d4c7-d152-4acf-a67d-6edddcc37892.png) |
> feat: change the order of the sections in the header

- src/theme/components/Card.tsx
- src/theme/components/Layout.tsx
- src/theme/sections/Libraries.tsx
<table><tbody><tr><td>Before</td><td>Now</td></tr><tr><td><figure class="image"><img src="https://user-images.githubusercontent.com/4921914/222780454-82ce9ef8-2491-46ed-8a9c-3f6215ae2e39.png"></figure></td><td><figure class="image"><img src="https://user-images.githubusercontent.com/4921914/222780521-f6852ec2-2085-4176-acbc-71345288e7fa.png"></figure></td></tr></tbody></table>
> fix: fix the size of the bottom space of the `Librairies` section

- src/theme/components/Section.tsx
<table><tbody><tr><td>Before</td><td>Now</td></tr><tr><td><figure class="image"><img src="https://user-images.githubusercontent.com/4921914/222773459-6a6f789e-8756-46cb-8c2d-cb9e4ffa08ae.png"></figure></td><td><figure class="image"><img src="https://user-images.githubusercontent.com/4921914/222773404-13bba0c2-ad17-4420-a31d-064fd9e030d3.png"></figure></td></tr></tbody></table>
> feat(mobile): change the section background on mobile format

- src/pages/model-generation-application.tsx
- src/sections/home/ModelGenerationApp.tsx
- src/theme/components/Post.tsx
- src/theme/components/Section.tsx
- src/theme/components/material-kit/Navbar/Navbar.tsx
- src/theme/components/material-kit/Navbar/common/NavbarItem.tsx
- src/theme/components/material-kit/Navbar/mobile/DropdownDropdown.tsx
- src/theme/components/material-kit/Navbar/mobile/DropdownLink.tsx
- src/theme/utils/helpers.ts
- Home page
- Remove top margin for the first section on the mobile view
- Fix the style of the ModelGenerationApp section on mobile view
- Set the number max of news/posts to 3 on mobile, 6 on desktop (previously, it was always 8)
- Fix the design of the model generation app page on mobile view
- Fix the hover style on the navbar on mobile view
> feat: improve the design of the mobile view

- .github/dependabot.yml
We mainly work on the website on Friday. So handle npm dependencies and GitHub actions update that day. This will reduce the workload and notifications during the rest of the week
> chore: run dependabot on friday

- src/content/LibraryContent.tsx
- src/sections/home/Libraries.tsx
- src/theme/components/Library.tsx
- src/theme/components/index.tsx
- src/theme/types.ts
> refactor(props): refactor library props

- src/assets/theme/base/globals.ts
- src/assets/theme/index.ts
- src/components/material-kit/MKTypography/MKTypographyRoot.tsx
- src/pages/model-generation-application-conditions.tsx
- src/pages/model-generation-application.tsx
⚠️ The text doesn't have the same font size as the original design, due to the `Typography` of Material Kit. But, I think it make the rendering more readable.  
Covers #831
> feat(page): use MaterialUI in the model generation application page

- src/pages/model-generation-application-conditions.tsx
- src/pages/model-generation-application.tsx
⚠️ The text doesn't have the same font size as the original design, due to the `Typography` of Material Kit. But, I think it make the rendering more readable.  
Covers #831
> feat(page): use MaterialUI in the model generation application conditions page

- src/components/modelGenerationApp/CardWithIcon.tsx
- src/components/modelGenerationApp/Features.tsx
- src/pages/model-generation-application.tsx
Based on our team's decision, we no longer require approval of the refactoring pull request. Instead, we will review and approve the refactoring once all changes related to a specific component have been completed.  
:warning: The text doesn't have the same font size as the original design, due to the `Typography` of Material Kit. But, I think it make the rendering more readable.  
Covers [#831](https://github.com/process-analytics/process-analytics.dev/issues/831)
> feat(model generation app): use MaterialUI in the ModelGenerationApplication components

- src/components/Section.tsx
- src/components/modelGenerationApp/Features.tsx
⚠️ The text can have not the same font size as the original design, due to the Typography of Material Kit.   
Covers #831
> feat(section): use MaterialUI in the Section component

- src/assets/theme/base/borders.ts
- src/assets/theme/base/globals.ts
- src/assets/theme/base/typography.ts
- src/assets/theme/components/muiCard.ts
- src/assets/theme/components/muiContainer.ts
- src/assets/theme/components/muiIcon.ts
- src/assets/theme/components/muiSvgIcon.ts
- src/assets/theme/components/muiTooltip.ts
- src/types/@mui-material-styles.d.ts
Currently, there is a mix in the configuration of the Material UI theme. We use a part of the configuration from Material Kit and a part of the old CSS configuration from the old theme.
To avoid to have to fix it at each new integration of component from Material Kit or Material UI, I do the following actions:
- Removed the configuration of the old theme in the Material UI theme,
- Uses the theme configuration from Material Kit for the existing configuration of Material UI. 
ℹ️ Based on our team's decision, we no longer require approval of the refactoring pull request. Instead, we will review and approve the refactoring once all changes related to a specific component have been completed.
> feat(theme): use the config from Material Kit for the theme of Material UI

- src/components/MarkdownComponents.tsx
- src/components/description/MDXPanel.tsx
- src/content/about_content_3.mdx
⚠️ The text can have not the same font size as the original design, due to the Typography of Material Kit.
> feat(mdx): use MaterialUI in the styled components for the MDX content

- src/assets/css/cookieconsent.css
- src/assets/css/global.css
- src/assets/theme/base/typography.ts
- src/assets/theme/components/muiCssBaseline.ts
https://github.com/creativetimofficial/material-kit-react/blob/main/src/assets/theme/base/typography.js
> feat(font family): use the font of Material Kit

- gatsby-config.ts
Change the gastby configuration for `gatsby-plugin-google-gtag` plugin when the website is build in development mode and there is no `trackingIds`.
ℹ️ Based on our team's decision, we no longer require approval of the refactoring pull request. Instead, we will review and approve the refactoring once all changes related to a specific component have been completed.
Closes #1140
> chore(gatsby): update the gastby configuration

- eslint.config.mjs
- package-lock.json
- package.json
*   use [extends](https://typescript-eslint.io/packages/typescript-eslint/#flat-config-extends) feature of typescript-eslint only on `tseslint.configs.recommended` and `tseslint.configs.stylistic`, because there are not by default apply on Typescript files and the Eslint way to apply on those files doesn't work.
* avoid unnecessary configuration of plugin and parser.
* execute eslint only on files of `src` folder and on root files, not `build` or `node_modules`.
Actually, the new feature to ignore folders in conf file or in commande line, seems to not work after several tests: https://eslint.org/docs/latest/use/configure/ignore.
> chore: fix eslint config
